spring:
    #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.33.88:3306/my_works?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 521541
    tomcat:
      default-auto-commit: true
      initial-size: 3
      max-active: 100
      max-wait: 1000
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 120000
